### ISSUE TITLE
Do I need to preprocess before I can use it

### ISSUE THREAD

**Issue by jacksinofn** [Sally-SH/VSP-LLM#3]
I want to conduct a simple inference test on how to use it. I downloaded checkpoint. pt, but I don't know how to perform inference.

**Comment by JeongHun0716** [comment]
Thank you for your question.

In order to simple inference test, firstly, you need to download the LRS3  dataset. Then, you download the landmarks of each video from this link(https://github.com/mpc001/auto_avsr/tree/main/preparation) to crop mouth region from videos.

We have additionally uploaded files related to the test set into the labels folder. You can modify only the dataset path using the replace_path.py file located in src/dataset, and then move the pretrained model(llama2 and checkpoint_finetune.pt) to the checkpoints folder. Finally, you can inference test by using decode.sh file.
